In [2]:
for i in range(0,3):
    print(i)

0
1
2


In [69]:
8 % 4

0

In [7]:
def is_leap(year):
    leap = False
    
    # Write your logic here
    if year % 4 != 0:
        pass
    elif year % 4 == 0:
        if year % 100 != 0:
            leap = True
        else:
            if year % 400 == 0:
                leap = True
    
    return leap

year = 2000
print(is_leap(year))

True


In [70]:
n = int(input())
for i in range (1, n+1):
    print(i, end='')


12345

In [77]:
n = int(input())
for i in range(1, n+1):
    print(i, end=' ')


1 2 3 4 5 

In [89]:
teste = [i for i in range(0,3)]

In [91]:
teste.reverse()

In [92]:
teste

[2, 1, 0]

In [6]:
x = 1
y = 1
z = 2
n = 3
[[i, j, k] for i in range(x + 1)
                          for j in range(y + 1)
                          for k in range(z + 1)
                        #   if i + j + k != n
                          ]

[[0, 0, 0],
 [0, 0, 1],
 [0, 0, 2],
 [0, 1, 0],
 [0, 1, 1],
 [0, 1, 2],
 [1, 0, 0],
 [1, 0, 1],
 [1, 0, 2],
 [1, 1, 0],
 [1, 1, 1],
 [1, 1, 2]]

# Listas

In [22]:
N = 3
lista = []
    
for i in range(N):
    comando = input()
    operacao = comando.split()[0]
    qtd_params_comando = len(comando.split())

    if qtd_params_comando == 3:
        indice = int(comando.split()[1])
        elemento = int(comando.split()[2])
    elif qtd_params_comando == 2:
        elemento = int(comando.split()[1])
        
    
    if operacao == 'append':
        lista.append(elemento)
    elif operacao == 'insert':
        # lista.append(0)
        lista.insert(indice, elemento)
    elif operacao == 'print':
        print(lista)
    elif operacao == 'remove':
        lista.remove(elemento)
    elif operacao == 'sort':
        lista.sort()
    elif operacao == 'pop':
        lista.pop()
    elif operacao == 'reverse':
        lista.reverse()

[5]
[6]
[6]


In [94]:
N = 3
lista = []
    
for _ in range(N):
    comando, *args = input().split()
    print(args)

['b', 'c', 'd', 'e']
['2', '3', '4', '5']
['xyz', 'abcd']


## lambda
Funções anônimas definidas em uma única linha, usadas para tarefas simples e rápidas!
> lambda argumentos: expressão

In [110]:
dobro = lambda x: x * 2
dobro(5)

10

In [111]:
soma = lambda x, y: x + y
soma(2, 2)

4

## map
Aplica uma função a cada item de um iterável (como lista ou tupla) e retorna um iterador com os resultados!
> map(função, iterável)

In [112]:
nums = [1, 2, 3, 4]
squares = map(lambda x: x**2, nums)
list(squares)

[1, 4, 9, 16]

## filter
Aplica uma função a cada elemento de um iterável e retorna apenas os elementos para os quais a função retorna True
> filter(função, iterável)

In [113]:
nums = [1, 2, 3, 4, 5, 6]
pares = filter(lambda x: x % 2 == 0, nums)
list(pares)

[2, 4, 6]

## sorted
Retorna um novo ITERÁVEL (lista, tuplas ou dicionários) ortenada a partir de um iterável. Pode ordenar em ordem crescente, decrescente e aceitar uma função com critérios 
> sorted(iterável, key=função, reverse=False)
- key: Função usada para personalizar a ordenação
- reverse: Se true, ordena em ordem decrescente

In [114]:
nums = [3, 1, 4, 2]
sorted(nums)

[1, 2, 3, 4]

In [117]:
# Ordenar strings pelo tamanho
palavras = ['banana', 'maçã', 'kiwi']
ordenadas = sorted(palavras, key=lambda x: len(x), reverse=True)
ordenadas

['banana', 'maçã', 'kiwi']

# Tuplas

In [104]:
# n = int(input())
integer_list = map(int, input().split())

In [105]:
integer_list

In [106]:
list(integer_list)

[1, 2, 3, 4, 5]

# Concatenate

In [6]:
import numpy as np

N_M_P = map(int, input().split())
lista_NMP = list(N_M_P)
N_P = []
M_P = []

for n in range(lista_NMP[0]):
    element = list(map(int, input().split()))
    N_P.append(element)

for m in range(lista_NMP[1]):
    element = list(map(int, input().split()))
    M_P.append(element)

print(np.concatenate((N_P, M_P)))

In [12]:
hash('a')

-6287813715396242540

# Swap Cases

In [118]:
s = 'Olá'
new_string = []

# for letter in s:
    # print(letter, letter.islower())
    # if letter.islower():
    #     new_string.append(letter.upper())
    # else:
    #     new_string.append(letter.lower())

print(s.swapcase())

oLÁ


In [122]:
'--'.join(s)

'O--l--á'

# String validators

In [123]:
s = 'AA1A#'

s.isupper()

True

In [127]:
[letra for letra in s if letra.isalnum()]

['A', 'A', '1', 'A']

In [128]:
[letra for letra in s if letra.isalpha()]

['A', 'A', 'A']

In [129]:
[letra for letra in s if letra.isdigit()]

['1']

In [130]:
[letra for letra in s if letra.islower()]

[]

In [131]:
[letra for letra in s if letra.isupper()]

['A', 'A', 'A']

In [ ]:
has_alphanum = ''.join([letra for letra in s if letra.isalnum()]).isalnum()
has_alpha = ''.join([letra for letra in s if letra.isalpha()]).isalpha()
has_digits = ''.join([letra for letra in s if letra.isdigit()]).isdigit()
has_lower = ''.join([letra for letra in s if letra.islower()]).islower()
has_upper = ''.join([letra for letra in s if letra.isupper()]).isupper()

In [58]:
print(''.join([letra for letra in s if letra.isalnum()]).isalnum())
print(''.join([letra for letra in s if letra.isalpha()]).isalpha())
print(''.join([letra for letra in s if letra.isdigit()]).isdigit())
print(''.join([letra for letra in s if letra.islower()]).islower())
print(''.join([letra for letra in s if letra.isupper()]).isupper())

True
True
True
False
True


# Text alignment

In [65]:
width = 100
print('HackerRank'.ljust(width,'-'))
print('HackerRank'.center(width,'-'))
print('HackerRank'.rjust(width,'-'))

HackerRank------------------------------------------------------------------------------------------
---------------------------------------------HackerRank---------------------------------------------
------------------------------------------------------------------------------------------HackerRank


## Tapete

In [132]:
import math

numbers = "7 21"

N, M = int(numbers.split()[0]), int(numbers.split()[1])

metade = math.ceil(N/2)

desenho_a = '.|.'
desenho_b = '-'

c = 1

for i in range(1, N+1):
    if i < metade:
        print((desenho_a * c).center(M, desenho_b))
        c += 2
    elif i == metade:
        print('WELCOME'.center(M, desenho_b))
    else:
        c -= 2
        print((desenho_a * c).center(M, desenho_b))

---------.|.---------
------.|..|..|.------
---.|..|..|..|..|.---
-------WELCOME-------
---.|..|..|..|..|.---
------.|..|..|.------
---------.|.---------


In [135]:
import math

N, M = 7, 21  # Ou qualquer outra entrada
desenho_a = '.|.'
desenho_b = '-'

# Metade superior
for i in range(1, N, 2):
    print((desenho_a * i).center(M, desenho_b))

# Linha do meio
print('WELCOME'.center(M, desenho_b))

# Metade inferior
for i in range(N - 2, 0, -2):
    print((desenho_a * i).center(M, desenho_b))


---------.|.---------
------.|..|..|.------
---.|..|..|..|..|.---
-------WELCOME-------
---.|..|..|..|..|.---
------.|..|..|.------
---------.|.---------


## Decimal / Octal / Hexadecimal / Binary

In [136]:
number = 17

pad = len("{0:b}".format(number))

for i in range(1, number+1):
    print(str(i).rjust(pad), oct(i)[2:].rjust(pad), hex(i)[2:].upper().rjust(pad), "{0:b}".format(i).rjust(pad))

    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


In [140]:
number = 17

pad = len(bin(number)[2:])

for i in range(1, number+1):
    print(
        f"{str(i).rjust(pad)} {oct(i)[2:].rjust(pad)} {hex(i)[2:].upper().rjust(pad)} {bin(i)[2:].rjust(pad)}"
    )

    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


## Capitalize

In [ ]:
nome = '1 w 2 r 3g'
list(map(lambda x: x.capitalize(), nome.split()))

In [155]:
nome = 'hello   world  lol'
list(map(lambda x: x.capitalize(), nome.split()))

['Hello', 'World', 'Lol']

In [154]:
nome.title()

'1 W 2 R 3G'

In [159]:
import re

nome = 'hello   world  lol'
result = map(lambda x: x.capitalize(), re.split(r'(\s+)', nome))
print(list(result))


['Hello', '   ', 'World', '  ', 'Lol']


In [ ]:
s = 'hello   world  lol'
words = s.split(" ")

for i in range(len(words)):
    if words[i]:  # verifica se não é uma string vazia
        words[i] = words[i][0].upper() + words[i][1:]


In [166]:
words

['hello', '', '', 'world', '', 'lol']

In [163]:
" ".join(words)

'Hello   World  Lol'

In [164]:
" ".join(word.capitalize() for word in s.split())

'Hello World Lol'

## itertools

### product

In [2]:
from itertools import product

In [3]:
a = input()
b = input()

In [9]:
list_a = list(map(int, a.split()))
list_b = list(map(int, b.split()))

In [15]:
cart_prod = list(product(list_a, list_b))

In [17]:
for i in cart_prod:
    print(i, end=" ")

(1, 3) (1, 4) (2, 3) (2, 4) 

### permutations

In [18]:
from itertools import permutations

In [42]:
user_input = input()

In [43]:
palavra, k = user_input.split()[0], int(user_input.split()[1])

In [44]:
list_letters = list(palavra)

In [45]:
list_letters.sort()

In [46]:
list_permutations = list(permutations(list_letters, k))

In [48]:
k

4

In [51]:
for i in list_permutations:
    print(''.join(i))

ABCD
ABCE
ABCF
ABDC
ABDE
ABDF
ABEC
ABED
ABEF
ABFC
ABFD
ABFE
ACBD
ACBE
ACBF
ACDB
ACDE
ACDF
ACEB
ACED
ACEF
ACFB
ACFD
ACFE
ADBC
ADBE
ADBF
ADCB
ADCE
ADCF
ADEB
ADEC
ADEF
ADFB
ADFC
ADFE
AEBC
AEBD
AEBF
AECB
AECD
AECF
AEDB
AEDC
AEDF
AEFB
AEFC
AEFD
AFBC
AFBD
AFBE
AFCB
AFCD
AFCE
AFDB
AFDC
AFDE
AFEB
AFEC
AFED
BACD
BACE
BACF
BADC
BADE
BADF
BAEC
BAED
BAEF
BAFC
BAFD
BAFE
BCAD
BCAE
BCAF
BCDA
BCDE
BCDF
BCEA
BCED
BCEF
BCFA
BCFD
BCFE
BDAC
BDAE
BDAF
BDCA
BDCE
BDCF
BDEA
BDEC
BDEF
BDFA
BDFC
BDFE
BEAC
BEAD
BEAF
BECA
BECD
BECF
BEDA
BEDC
BEDF
BEFA
BEFC
BEFD
BFAC
BFAD
BFAE
BFCA
BFCD
BFCE
BFDA
BFDC
BFDE
BFEA
BFEC
BFED
CABD
CABE
CABF
CADB
CADE
CADF
CAEB
CAED
CAEF
CAFB
CAFD
CAFE
CBAD
CBAE
CBAF
CBDA
CBDE
CBDF
CBEA
CBED
CBEF
CBFA
CBFD
CBFE
CDAB
CDAE
CDAF
CDBA
CDBE
CDBF
CDEA
CDEB
CDEF
CDFA
CDFB
CDFE
CEAB
CEAD
CEAF
CEBA
CEBD
CEBF
CEDA
CEDB
CEDF
CEFA
CEFB
CEFD
CFAB
CFAD
CFAE
CFBA
CFBD
CFBE
CFDA
CFDB
CFDE
CFEA
CFEB
CFED
DABC
DABE
DABF
DACB
DACE
DACF
DAEB
DAEC
DAEF
DAFB
DAFC
DAFE
DBAC
DBAE
DBAF
DBCA
DBCE
DBCF
DBEA
DBEC


### combinations

In [84]:
from itertools import combinations, chain

In [53]:
user_input = input()

In [61]:
string, k = user_input.split()

In [67]:
list_letters = list(string)
list_letters.sort()

In [68]:
list_letters

['A', 'C', 'H', 'K']

In [78]:
combs = []
for i in range(1, int(k)+1):
    combs.append(list(combinations(list_letters, i)))

In [85]:
flat_list = list(chain.from_iterable(combs))

In [89]:
for i in flat_list:
    print(''.join(i))

A
C
H
K
AC
AH
AK
CH
CK
HK


### combinations with replacement

In [98]:
from itertools import combinations_with_replacement

In [90]:
user_input = input()

In [92]:
string, k = user_input.split()

In [96]:
list_letters = list(string)
list_letters.sort()

In [102]:
combs = list(combinations_with_replacement(list_letters, int(k)))

In [103]:
for i in combs:
    print(''.join(i))

AA
AC
AH
AK
CC
CH
CK
HH
HK
KK


## Problem solving

In [8]:
''.join(list(set('ADA')))

'AD'

In [33]:
s = 'AABCAAADA'
k = 3

In [34]:
list_letters = list(s)

In [35]:
list_letters

['A', 'A', 'B', 'C', 'A', 'A', 'A', 'D', 'A']

In [37]:
for i in range(0,len(list_letters), k):
    print(''.join(list(set(list_letters[i:i+k]))))

AB
CA
AD


## Numpy

### identity
- Tipo default: float

In [41]:
import numpy as np
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
print(np.eye(8,7, k=1))

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [44]:
import numpy as np
np.set_printoptions(legacy='1.13')

In [1]:
input = input()
N, M = map(int, input.split())

ValueError: not enough values to unpack (expected 2, got 0)

In [48]:
np.eye(N, M, k=0)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### Funções matemáticas

In [50]:
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print(a + b)                     #[  6.   8.  10.  12.]
print(numpy.add(a, b))           #[  6.   8.  10.  12.]

print(a - b)                    #[-4. -4. -4. -4.]
print(numpy.subtract(a, b))     #[-4. -4. -4. -4.]

print(a * b)                     #[  5.  12.  21.  32.]
print(numpy.multiply(a, b))      #[  5.  12.  21.  32.]

print(a / b)                     #[ 0.2         0.33333333  0.42857143  0.5       ]
print(numpy.divide(a, b))        #[ 0.2         0.33333333  0.42857143  0.5       ]

print(a % b)                     #[ 1.  2.  3.  4.]
print(numpy.mod(a, b))           #[ 1.  2.  3.  4.]

print(a**b)                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
print(numpy.power(a, b))         #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


[  6.   8.  10.  12.]
[  6.   8.  10.  12.]
[-4. -4. -4. -4.]
[-4. -4. -4. -4.]
[  5.  12.  21.  32.]
[  5.  12.  21.  32.]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 1.  2.  3.  4.]
[ 1.  2.  3.  4.]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


In [11]:
import numpy as np
n, m = list(map(int, input().split()))

In [12]:
list(map(int, input().split()))

[1, 2, 3, 4]

In [13]:
[list(map(int, input().split()))]

[[1, 2, 3, 4]]

In [14]:
A = [list(map(int, input().split())) for _ in range(n)]
B = [list(map(int, input().split())) for _ in range(n)]

In [15]:
a = np.array(A)
b = np.array(B)

In [16]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.floor_divide(a, b))
print(np.mod(a, b))
print(np.power(a, b))

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### Floor, Ceil and Rint

In [17]:
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(numpy.floor(my_array))         #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [18]:
my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(numpy.ceil(my_array))          #[  2.   3.   4.   5.   6.   7.   8.   9.  10.]

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [19]:
my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(numpy.rint(my_array))          #[  1.   2.   3.   4.   6.   7.   8.   9.  10.]

[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [20]:
import numpy as np
np.set_printoptions(legacy='1.13')

In [ ]:
A = list(map(float, input().split()))

In [24]:
A

[1.1, 2.2, 3.3]

In [26]:
a = np.array(A)
a

array([ 1.1,  2.2,  3.3])

In [27]:
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

[ 1.  2.  3.]
[ 2.  3.  4.]
[ 1.  2.  3.]


### Sum and Prod

In [ ]:
# By default, the axis value is None. 
# Therefore, it performs a sum over all the dimensions of the input array.
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print(numpy.sum(my_array, axis = 0))         #Output : [4 6]
print(numpy.sum(my_array, axis = 1))         #Output : [3 7]
print(numpy.sum(my_array, axis = None))      #Output : 10
print(numpy.sum(my_array))                   #Output : 10

[4 6]
[3 7]
10
10


In [ ]:
# By default, the axis value is None. 
# Therefore, it performs the product over all the dimensions of the input array.
print(numpy.prod(my_array, axis = 0))            #Output : [3 8]
print(numpy.prod(my_array, axis = 1))            #Output : [ 2 12]
print(numpy.prod(my_array, axis = None))         #Output : 24
print(numpy.prod(my_array))                      #Output : 24

[3 8]
[ 2 12]
24
24


In [30]:
import numpy as np

N, M = (map(int, input().split()))

In [31]:
N, M

(2, 2)

In [33]:
l = []
for _ in range(N):
    l.append(list(map(int, input().split())))

In [35]:
array = np.array(l)

In [ ]:
soma = np.sum(array, axis=0)
print(np.prod(soma))

[4 6]
24


### Shape and reshap
- The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.
- The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself.

In [231]:
import numpy
my__2D_array = numpy.array([[1, 2],[3, 4],[6,5]])
print(my__2D_array.shape)     #(3, 2) -> 3 rows and 2 columns 

(3, 2)


In [232]:
change_array = numpy.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
print(change_array)

[[1 2]
 [3 4]
 [5 6]]


In [233]:
my_array = numpy.array([1,2,3,4,5,6])
print(numpy.reshape(my_array,(3,2)))

[[1 2]
 [3 4]
 [5 6]]


In [7]:
import numpy as np
input_integers = np.array(list(map(int, input().split())))

In [10]:
print(np.reshape(input_integers, (3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Collections

## Counter

In [1]:
from collections import Counter

In [15]:
myList = [1,1,2,3,4,5,3,2,3,4,2,1,2,3]
c = Counter(myList)

In [16]:
c

Counter({2: 4, 3: 4, 1: 3, 4: 2, 5: 1})

In [17]:
c.subtract([2])
c

Counter({3: 4, 1: 3, 2: 3, 4: 2, 5: 1})

In [9]:
print(dict(Counter(myList)))

{1: 3, 2: 4, 3: 4, 4: 2, 5: 1}


In [4]:
print(Counter(myList).items())

dict_items([(1, 3), (2, 4), (3, 4), (4, 2), (5, 1)])


In [5]:
print(Counter(myList).keys())

dict_keys([1, 2, 3, 4, 5])


In [6]:
print(Counter(myList).values())

dict_values([3, 4, 4, 2, 1])


### Exercício

In [32]:
# Quantidade de sapatos
X = int(input())
X

10

In [39]:
shoe_sizes = list(map(int, input().split()))
shoe_sizes

[2, 3, 4, 5, 6, 8, 7, 6, 5, 18]

In [54]:
c = Counter(shoe_sizes)
c

Counter({5: 2, 6: 2, 2: 1, 3: 1, 4: 1, 8: 1, 7: 1, 18: 1})

In [35]:
# Quantidade de clientes
N = int(input())
N

6

In [55]:
earned_money = 0

for _ in range(N):
    shoe_size, shoe_price = tuple(map(int, input().split()))

    if c[shoe_size] > 0:
        c.subtract([shoe_size])
        earned_money += shoe_price

In [56]:
earned_money

200

In [52]:
c[6]

-1

In [44]:
c.subtract([9])

In [48]:
9 in c

False

## Deque
- A deque is a double-ended queue. It can be used to add or remove elements from both ends.

In [60]:
from collections import deque
d = deque()
d.append(1)
print(d)

deque([1])


In [61]:
d.appendleft(2)
d

deque([2, 1])

In [72]:
d.clear()
d

deque([])

In [73]:
d.extend('1')
d

deque(['1'])

In [74]:
d.extend([2, 3])
d

deque(['1', 2, 3])

In [75]:
d.extendleft('234')
d

deque(['4', '3', '2', '1', 2, 3])

In [76]:
d.count('1')

1

In [77]:
d

deque(['4', '3', '2', '1', 2, 3])

In [78]:
d.pop()

3

In [79]:
d

deque(['4', '3', '2', '1', 2])

In [80]:
d.popleft()

'4'

In [81]:
d

deque(['3', '2', '1', 2])

In [82]:
d.remove('2')

In [83]:
d

deque(['3', '1', 2])

In [84]:
d.reverse()
d

deque([2, '1', '3'])

In [85]:
d.rotate(1)
d

deque(['3', 2, '1'])

### Exercício

In [101]:
N = int(input())

d = deque()

for _ in range(N):
    user_input = input()

    if ' ' in user_input:
        metodo, valor = user_input.split()
    else:
        metodo = user_input

    valor = int(valor)

    if metodo == 'append':
        d.append(valor)
    elif metodo == 'appendleft':
        d.appendleft(valor)
    elif metodo == 'pop':
        d.pop()
    elif metodo == 'popleft':
        d.popleft()

entrou no metodo append
entrou no metodo append
entrou no metodo append


In [104]:
for i in range(len(d)):
    print(d[i], end=' ')

1 2 

# Exercício: Empilhando cubos

In [152]:
from collections import deque

T = int(input())

for _ in range(T):
    n = int(input())
    blocks = deque(list(map(int, input().split())))
    stack = deque()
    

    element_to_add = None
    result = None

    while True:
        if len(blocks) == 0:
            print('Yes')
            break

        first_element = blocks[0]
        last_element = blocks[-1]
        
        if last_element > first_element:
            element_to_add = last_element
        else:
            element_to_add = first_element

        if len(stack) == 0:
            stack.append(element_to_add)
            blocks.remove(element_to_add)
        elif stack[-1] >= element_to_add:
            stack.append(element_to_add)
            blocks.remove(element_to_add)
        else:
            result = 'No'
            print(result)
            break

Yes
No


In [158]:
from collections import deque

T = int(input())

for _ in range(T):
    n = int(input())
    blocks = deque(map(int, input().split()))

    # Começa com o valor máximo teórico
    last_added = float('inf')
    result = "Yes"

    while blocks:
        # Verifica os extremos da fila
        if blocks[0] >= blocks[-1]:
            element_to_add = blocks.popleft()
        else:
            element_to_add = blocks.pop()

        # Verifica se a ordem está correta
        if element_to_add > last_added:
            result = "No"
            break

        # Atualiza o topo da pilha
        last_added = element_to_add

    print(result)


2
inf
3
2
No


In [153]:
float('inf')

inf

In [129]:
stack

deque([7])

In [130]:
blocks

deque([1, 2, 3, 8])

## Exercício: Company Logo
- logo = 3 caracteres mais comuns no nome

In [181]:
from collections import Counter
s = input()
list_comp_name = list(s)

counter = Counter(list_comp_name)
sorted_items = sorted(counter.items(), key=lambda x: (-x[1], x[0]))

for i in range(3):
    print(sorted_items[i][0], sorted_items[i][1])

g 2
o 2
e 1


## OrderedDict
An OrderedDict is a dictionary that remembers the order of the keys that were inserted first. If a new entry overwrites an existing entry, the original insertion position is left unchanged.

In [182]:
from collections import OrderedDict

ordinary_dictionary = {}
ordinary_dictionary['a'] = 1
ordinary_dictionary['b'] = 2
ordinary_dictionary['c'] = 3
ordinary_dictionary['d'] = 4
ordinary_dictionary['e'] = 5

print(f'Dicionário normal: {ordinary_dictionary}')

ordered_dictionary = OrderedDict()
ordered_dictionary['a'] = 1
ordered_dictionary['b'] = 2
ordered_dictionary['c'] = 3
ordered_dictionary['d'] = 4
ordered_dictionary['e'] = 5

print('Dicionário ordenado:', ordered_dictionary)

Dicionário normal: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
Dicionário ordenado: OrderedDict([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)])


In [218]:
N = int(input())
ordered_dict = OrderedDict()

In [219]:
for _ in range(N):
    user_input = input()
    entradas = user_input.split()
    qtd_entradas = len(entradas)

    if qtd_entradas > 2:
        qtd_palavras_produto = qtd_entradas - 1
        item_name = ' '.join(entradas[:qtd_palavras_produto])
        net_price = int(entradas[-1])
    else:
        item_name = entradas[0]
        net_price = int(entradas[-1])

    if item_name in ordered_dict:
        ordered_dict[item_name] += net_price
    else:
        ordered_dict[item_name] = net_price
        

In [221]:
for key, value in ordered_dict.items():
    print(key, value)

BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


## Exercício: Word Order

In [222]:
n = int(input())
ordered_dict = OrderedDict()

for _ in range(n):
    word = input().strip()

    if word not in ordered_dict:
        ordered_dict[word] = 1
    else:
        ordered_dict[word] += 1

In [224]:
print(len(ordered_dict))


3

In [228]:
for i in ordered_dict.values():
    print(i, end= ' ')

2 1 1 

## DefaultDict
A única diferença para um dicionário normal é que tem um default value para chaves ainda não configuradas!

In [106]:
from collections import defaultdict
d = defaultdict(list)
d['python'].append("awesome")
d['something-else'].append("not relevant")
d['python'].append("language")
for i in d.items():
    print(i)

('python', ['awesome', 'language'])
('something-else', ['not relevant'])


In [108]:
d['teste']

[]

### Exercício

In [111]:
n, m = list(map(int, input().split()))

In [126]:
d = defaultdict(list)
for i in range(n):
    word = input()
    d[word].append(i + 1)

for _ in range(m):
    word = input()
    if len(d[word]) > 0:
        print(' '.join([str(s) for s in d[word]]))
    else:
        print(-1)

1 2 4
3 5


In [124]:
d['a']

[1, 2, 4]

In [122]:
d

defaultdict(list, {'a': [1, 2, 4], 'b': [3, 5]})

## Named tuple
They turn tuples into convenient containers for simple tasks.
With namedtuples, you don’t have to use integer indices for accessing members of a tuple.

In [127]:
from collections import namedtuple
Point = namedtuple('Point','x,y')
pt1 = Point(1,2)
pt2 = Point(3,4)
dot_product = ( pt1.x * pt2.x ) +( pt1.y * pt2.y )
print(dot_product)

11


In [128]:
pt1.x

1

In [129]:
pt2.x

3

In [131]:
Car = namedtuple('Car','Price Mileage Colour Class')
xyz = Car(Price = 100000, Mileage = 30, Colour = 'Cyan', Class = 'Y')
print(xyz)
print(xyz.Class)

Car(Price=100000, Mileage=30, Colour='Cyan', Class='Y')
Y


### Exercício

In [ ]:
Student = namedtuple('Student', 'marks ids name class')

# Regex and Parsing

## Part 1

In [52]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print("Start :", tag)
        for attr in attrs:
            print('->', attr[0], '>', attr[1])

    def handle_endtag(self, tag):
        print("End   :", tag)

    def handle_startendtag(self, tag, attrs):
        print("Empty :", tag)
        for attr in attrs:
            print('->', attr[0], '>', attr[1])

    def handle_data(self, data):
        ...


In [53]:
string = ('<meta http-equiv="refresh" content="5;url=http://example.com/" />')

In [54]:
string

'<meta http-equiv="refresh" content="5;url=http://example.com/" />'

In [55]:
parser = MyHTMLParser()
parser.feed(string)

Empty : meta
-> http-equiv > refresh
-> content > 5;url=http://example.com/


In [28]:
string = ''
N = int(input())
for _ in range(N):
    string += input()

parser = MyHTMLParser()
parser.feed(string)

Start : html
Start : head
Start : title
End   : title
End   : head
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


## Part 2

In [80]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        if "\n" in data:
            print(">>> Multi-line Comment")
        else:
            print(">>> Single-line Comment")
        print(data)

    def handle_data(self, data):
        if data.strip():
            print(">>> Data")
            print(data)

In [81]:
string = (
'<!--[if IE 9]>IE9-specific content\n'
'<![endif]-->'
'<div> Welcome to HackerRank</div>'
'<!--[if IE 9]>IE9-specific content<![endif]-->'
)

In [82]:
parser = MyHTMLParser()
parser.feed(string)

>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


In [ ]:
html = ''

for _ in range(int(input())):
    html += input().rstrip()
    html += '\n'

parser = MyHTMLParser()
parser.feed(html)

# Sets
A set is an unordered collection of elements without duplicate entries.
When printed, iterated or converted into a sequence, its elements will appear in an arbitrary order.

In [87]:
print(set([1,2,1,2,3,4,5,6,0,9,12,22,3]))

{0, 1, 2, 3, 4, 5, 6, 9, 12, 22}


In [88]:
set(['H','a','c','k','e','r','r','a','n','k'])

{'H', 'a', 'c', 'e', 'k', 'n', 'r'}

In [90]:
set(set(['H','a','c','k','e','r','r','a','n','k']))

{'H', 'a', 'c', 'e', 'k', 'n', 'r'}

In [91]:
set({'Hacker' : 'DOSHI', 'Rank' : 616 })

{'Hacker', 'Rank'}

## Exercício

In [98]:
N = int(input())
list_heights = list(map(int, input().split()))

In [100]:
distinct_heigts = set(list_heights)

In [102]:
n_distinct_heigts = len(distinct_heigts)

In [104]:
avg = sum(distinct_heigts) / n_distinct_heigts

In [105]:
avg

169.375

# Algoritmos

In [ ]:
lista = [1, 2, 3]

In [ ]:
sum(lista)

6

In [134]:
arr = [[11, 2, 4], [4, 5, 6], [10, 8, -12]]

In [136]:
qtd = len(arr)

In [139]:
[x for x in arr]

[[11, 2, 4], [4, 5, 6], [10, 8, -12]]

In [140]:
[arr[i][i] for i in range(len(arr))]

[11, 5, -12]

In [149]:
[arr[i][j-1] for i,j in zip(range(len(arr)), range(qtd, 0, -1))]

[4, 5, 10]

In [143]:
arr[0][2]

4

In [144]:
arr[1][1]

5

In [145]:
arr[2][0]

10

In [147]:
for i in range(qtd, 0, -1):
    print(i)

3
2
1


In [152]:
for i in range(2):
    print(i)

0
1


In [153]:
abs(-2)

2

In [154]:
arr = [-4, 3, -9, 0, 4, 1]

In [168]:
min(arr)

-9

In [ ]:
qtd_n = len(arr)
qtd_positive = sum([1 for i in arr if i > 0])
qtd_negative = sum([1 for i in arr if i < 0])
qtd_zero = sum([1 for i in arr if i == 0])

results = [qtd_positive/qtd_n, qtd_negative/qtd_n, qtd_zero/qtd_n]



In [159]:
results

[0.5, 0.3333333333333333, 0.16666666666666666]

In [ ]:
for result in range():
    print(result)

TypeError: 'list' object cannot be interpreted as an integer

In [160]:
teste = 'a'

In [166]:
for i in range(4-1, -1, -1):
    print(i)

3
2
1
0


In [167]:
n=4
for qtd_tralhas, qtd_wspaces in zip(range(1, n+1), range(n-1, -1, -1)):
        print(qtd_wspaces*' ', qtd_tralhas*'#', sep='')

   #
  ##
 ###
####


In [169]:
input = '07:05:45PM'

In [174]:
input[:2]

'07'

In [178]:
input[6:8]

'45'

In [190]:
s = '12:01:00AM'

In [205]:
indicator = s[-2:]
hour = int(s[:2])
minutes_seconds = s[3:8]
#  = s[6:8]

new_hour = None

if hour == 12:
    if indicator =='AM':
        new_hour = 0
    else:
        new_hour = 12
else:
    if indicator == 'AM':
        new_hour = hour
    else:
        new_hour = hour+12
        
if len(str(new_hour)) == 1:
    a='0'+str(new_hour)
else:
    a=(new_hour,':', minutes,':', seconds)

In [206]:
minutes_seconds

'01:00'

In [192]:
a

(None, ':', '01', ':', '00')

In [193]:
indicator

'AM'

In [194]:
hour

12

In [215]:
(((84 // 5)+1)*5) - 84

1

In [213]:
16 * 5

80

In [218]:
grades = [73, 67, 38, 33]
new_grades = []

for grade in grades:
    next_5_multiple = (((grade // 5)+1)*5)
    if grade < 38:
        new_grades.append(grade)
    elif next_5_multiple - grade < 3:
        new_grades.append(next_5_multiple)
    else:
        new_grades.append(grade)

In [219]:
new_grades

[75, 67, 40, 33]

In [221]:
print('\n'.join(map(str, new_grades)))
print('\n')


75
67
40
33




In [224]:
x1 = 0
v1 = 3
x2 = 4
v2 = 2

In [225]:
(x1 - x2) % (v1 - v2)

0

In [226]:
x1 - x2

-4

In [227]:
v1 - v2

1

In [10]:
scores = [10, 5, 20, 20, 4, 5, 2, 25, 1]

In [11]:
highest = 0
lowest = 0
n_least = 0
n_most = 0

for score in scores:
    if score < lowest:
        lowest = score
        n_least += 1
    elif score > highest:
        highest = score
        n_most += 1

In [31]:
s = [4]
d = 4
m = 1

In [37]:
n = 0
tamanho_barra = len(s)

for i in range(0, tamanho_barra):
    segmento = s[i:i+m]
    sum_segmento = sum(segmento)
    print(segmento, sum_segmento)
    if sum_segmento == d:
        n += 1


[4] 4


In [38]:
n

1

In [49]:
ar = [1, 3, 2, 6, 1, 2]
k = 3
tamanho_ar = len(ar)
n = 0
for i in range(tamanho_ar):
    for j in range(i+1, tamanho_ar):
        soma = ar[i] + ar[j]
        resto = soma % k
        
        if resto == 0:
            n += 1

1 3 4 1
1 2 3 0
1 6 7 1
1 1 2 2
1 2 3 0
3 2 5 2
3 6 9 0
3 1 4 1
3 2 5 2
2 6 8 2
2 1 3 0
2 2 4 1
6 1 7 1
6 2 8 2
1 2 3 0


In [50]:
n

5

In [73]:
from collections import Counter

arr = [2, 2, 1, 1, 3]

counter = Counter(arr)

In [74]:
max(counter, key=counter.get)

2

In [75]:
max(arr, key=arr.count)

2

In [108]:
year = 1800

In [ ]:
is_leap = False
    
if year == 1918:
    # transição
    result = f'26.09.{year}'
elif year < 1918:
    # julian
    if year % 4 == 0:
        is_leap = True

    if is_leap:
        result = f'12.09.{year}'
    else:
        result = f'13.09.{year}'
else:
    # gregorian
    if (year % 400 == 0) or ((year % 4 == 0) and (year % 100 != 0)):
        is_leap = True

    if is_leap:
        result = f'12.09.{year}'
    else:
        result = f'13.09.{year}'

In [110]:
result

'12.09.1800'

In [100]:
256 - 229

27

In [112]:
bill = [3, 10, 2, 9]
k = 1

In [113]:
cost_item_not_eaten = bill[k]
correct_amount = (sum(bill) - cost_item_not_eaten) / 2

if correct_amount == b:
    print('Bon Appetit')
else:
    print(cost_item_not_eaten)

10


In [116]:
5 % 2

1

In [117]:
5 - 1

4

In [118]:
3 % 2

1

In [119]:
3 - 1

2

In [122]:
ar = [10, 20, 20, 10, 10, 30, 50, 10, 20]

In [125]:
counter

Counter({10: 4, 20: 3, 30: 1, 50: 1})

In [131]:
counter = Counter(ar)
qtd_pares = 0

for cor,qtd in counter.items():
    print(cor, qtd)
    if qtd > 1:
        resto_div_2 = qtd % 2
        print(resto_div_2)
        if resto_div_2 == 0:
            qtd_pares += (qtd/2)
            print('multiplo 2----', qtd/2)
        else:
            qtd_pares += (qtd - resto_div_2)/2
            print('---', (qtd - resto_div_2)/2)

10 4
0
multiplo 2---- 2.0
20 3
1
--- 1.0
30 1
50 1


In [132]:
qtd_pares

3.0

In [133]:
2 - 1

1

In [134]:
6 - 2

4

In [135]:
3 - 1 

2

In [136]:
5 - 3

2

In [137]:
2-1

1

In [138]:
5 - 2

3

In [152]:
paginas = []
for i in range(n+1):
    paginas.append(i)

In [153]:
contador_inicio_ao_fim = 0
for i in range(0,len(paginas),2):
    print(paginas[i:i+2])
    subconjunto = paginas[i:i+2]
    if p in subconjunto:
        break
    contador_inicio_ao_fim += 1

[0, 1]
[2, 3]


In [154]:
contador_inicio_ao_fim

1

In [161]:
contador_fim_ao_inicio = 0
for i in range(len(paginas),0,-2):

[]
[5, 6]
[3, 4]
[1, 2]


In [223]:
n = 5
p = 4

In [224]:
resto_div_2 = n % 2

In [225]:
import math
n_pags_start_to_end = math.floor(p / 2)
n_pags_start_to_end

2

In [226]:
if resto_div_2 == 0:
    n_pags_end_to_start = math.ceil((n - p)/2)
else:
    n_pags_end_to_start = math.floor((n-p)/2)
n_pags_end_to_start

0

In [211]:
n-p

1

In [241]:
steps = 8
path = 'UDDDUDUU'

In [242]:
path

'UDDDUDUU'

In [243]:
def direction_value(d):
    if d == 'U':
        return 1
    return -1

In [244]:
path_values = list(map(direction_value, path))

In [252]:
valley = False
level = 0
valleys = 0

for s in path_values:
    level += s

    if level < 0:
        valley = True
    
    if valley and level >= 0:
        valleys += 1
        valley = False


In [253]:
valleys

1

In [273]:
bnm = input().split()

b = int(bnm[0])

n = int(bnm[1])

m = int(bnm[2])

keyboards = list(map(int, input().rstrip().split()))

drives = list(map(int, input().rstrip().split()))

In [274]:
price_combs = [-1]

In [279]:
for keyboard in keyboards:
    for usb in drives:
        # print(keyboard, usb, keyboard+usb)
        price_combs.append(keyboard + usb)

In [281]:
b

729580

In [282]:
max([price for price in price_combs if price <= b])

729580

## Between 2 Sets
Determine todos os inteiros que satisfaçam as seguintes condições:
1) Os elementos do primeiro array são todos múltiplos do inteiro sendo considerado
2) O inteiro sendo considerado é múltiplo de todos os elementos do segundo array

In [284]:
a = [2, 6]
b = [24, 36]

## Picking Numbers

In [340]:
a = [4, 6, 5, 3, 3, 1]

In [341]:
max_subarrays = 0
max_final_subarrays = 0

In [344]:
for i in range(len(a)):
    subarray = a[i:i+2]
    print(subarray)

    if len(subarray) > 1:
        first_element = subarray[0]
        second_element = subarray[1]
        diff = abs(first_element - second_element)
        
        print(first_element, second_element, diff)

        if diff <= 1:
            max_subarrays += 1
            print(f'{max_subarrays=}')
            
        elif diff > 1 :
            max_final_subarrays = max_subarrays
            max_subarrays = 0

            print(f'{max_subarrays=}')
            print(f'{max_final_subarrays=}')

        else:
            max_subarrays = 0

[4, 6]
4 6 2
max_subarrays=0
max_final_subarrays=0
[6, 5]
6 5 1
max_subarrays=1
[5, 3]
5 3 2
max_subarrays=0
max_final_subarrays=1
[3, 3]
3 3 0
max_subarrays=1
[3, 1]
3 1 2
max_subarrays=0
max_final_subarrays=1
[1]


In [343]:
max(max_subarrays, max_final_subarrays)

1